### ISSUE TITLE
User was not advised to save wallet address, which is needed for Restore; Question about recovery address eligibility; Repeated transaction failures

### ISSUE THREAD

**Issue by DylanCkawalec** [polymorpher/one-wallet#101]
as I was demonstrating the project to a potential client, I entered the application and see that I need to recover my address to open my account again. I was not prompted to save my address since I figured the authenticator would be the Login which I believe can be the solution. 

social recovery address. Can it be our own google chrome harmony 1 wallet or meta mask? I used my own wallet as a recovery address and the 1wallet did not recognize my recovery address.

 I made a new wallet and repeated the same task. The wallet works fine, but the transaction fails to send to an external wallet after the first 2 attempts. the 3rd attempt sent the transaction. 
 
 hope this helps :)

**Comment by polymorpher** [comment]
Sorry about that. I will add some warning message after a wallet is created, to ask the user either to save the address, or to get a domain name. The default domain name would be [the wallet's name].crazy.one. It would cost only 1 ONE. The name is consistent with the entry in Google Authenticator. When you restore, you can type the domain name instead and it would be automatically resolved to the address.

Social recovery address can be any valid address. You can use the Chrome extension address or MetaMask address. It should work. If it doesn't, it might be a bug in the browser client's code. I haven't had issues so far. If you can capture a screenshot / screen recording, that would help me find out what happened.

Sometimes transaction fail because the relayer thinks too many requests came from your browser within a short period of time. I will relax this limit. Another common reason is Harmony network being too busy. There is little I can do about that scenario. But I will add some analytics and keep monitoring cause of failures.

**Comment by polymorpher** [comment]
Concern #1 is fixed in https://github.com/polymorpher/one-wallet/pull/111

**Comment by polymorpher** [comment]
Concern (2) is fixed in https://github.com/polymorpher/one-wallet/commit/ceecc430cbb08065d7f8c4e22b31f810a4b99f7e

**Comment by polymorpher** [comment]
I relaxed rate limiter on relayer. Let me know if the issues persist.
