### ISSUE TITLE
Purchase of crazy.one subdomain from 1Wallet

### ISSUE THREAD

**Issue by BritishBully** [polymorpher/one-wallet#118]
It didn't prompt me to add my Twitter address during creation from 1Wallet, so now my subdomain doesn't show on my Twitter. (Also, there's no way to access the subdomain that I can see, but that's not a 1Wallet issue)

**Comment by polymorpher** [comment]
I haven't enabled the feature that links purchased domain to external identifiers. It can be activated later. The reason is the infrastructure could offer a lot more than just Twitter handle linkage, so we wanted to reserve the storage slot linked to the subdomain for later use, instead of just a Twitter handle. For example, it could store the wallet owner's profile image, personal website, Telegram id, and a lot more.

**Comment by BritishBully** [comment]
So, will 1Wallet be able to link to that subdomain later to update it?

**Comment by polymorpher** [comment]
Yes, owner of a subdomain (in this case, the 1wallet address) can update the storage slot of a subdomain at any time as long as the subdomain is not expired.
