### ISSUE TITLE
NFT not showing up under Collectibles 

### ISSUE THREAD

**Issue by vincentmah** [polymorpher/one-wallet#144]
Sent my NFT to my 1wallet, but it doesn't show up under collectibles. I can see it on the block explorer that it has been received.

**Comment by polymorpher** [comment]
What's your wallet address, and transaction id for the NFT transfer?

**Comment by vincentmah** [comment]
one1ah8kyf4weg08pcpjepeytarre7t55jwnaln4f4

0x1a5c96d7730a4f9d0688989ce65c6aca8b1cfd172ffb430483c43f3e88de217a

**Comment by polymorpher** [comment]
When I query your 1wallet address one1ah8kyf4weg08pcpjepeytarre7t55jwnaln4f4, it shows that the wallet has no "tracked tokens". This means the collectible's smart contract in question (ONECAN, at 0xf80790b2afc34390d5af12a3a332d12ff1886b42) does not implement ERC721 standard correctly even though it self-proclaims as a ERC721 NFT, since it does not call  `onERC721Received` of the recipient's address. See also https://docs.openzeppelin.com/contracts/2.x/api/token/erc721#IERC721Receiver-onERC721Received-address-address-uint256-bytes-

I can add a button later that let you manually track the token, so that it can be displayed in the wallet.

**Comment by polymorpher** [comment]
For further reference, the transfer transaction is https://explorer.harmony.one/tx/0x1aa7794df16e98fd8020a791028a6d504f3b853656d94193b7deaf6d6da5a79f?activeTab=2 . It shows a Transfer event was emitted, but the "Internal Transaction" tab shows the contract did not call `onERC721Received` as required by the spec.

**Comment by imajindev** [comment]
im having the same issue
wallet: one12afme6c9c4m9yll30wktrattvnv6suglan4gae
transaction: https://explorer.harmony.one/tx/0xf59fc775e83448688af1b95e4b3ba3db519d58df8cc3fb2f3d0f9fb0f68571ad

**Comment by polymorpher** [comment]
It was for the same reason. Were these things made by the same people?

**Comment by imajindev** [comment]
@polymorpher it may seems that to be the case. but sending the same nft to metamask wallet has nno issue
it will be able to display the nft in the wallet
and if you go to the wallet address in harmony explorer, you will be able to see the HRC721 token in the wallet
im not very clear with the technical intricacies, will you be able to shed some lights on this matter?

**Comment by polymorpher** [comment]
The apps (in this case, the NFT websites) generally notifies MetaMask when the NFT is purchased or interacted with using MetaMask. Upon receiving these notifications, MetaMask keeps a local record of what NFTs it should track. When the user enters the MetaMask wallet, it would look up what was tracked, read from the corresponding contracts, and display the NFT and the user's balance accordingly. 

In contrast, 1wallet does not get an opportunity to be notified like MetaMask, unless the app specifically implements 1wallet integration to notify 1wallet. Instead of relying on app's voluntary integrations, 1wallet also implements standard interfaces according to the ERC721 and 1155 specs to receive notification on-chain when an NFT is transferred to 1wallet.  See also https://github.com/polymorpher/one-wallet/wiki/Token-Tracking. NFT contracts that implement the ERC721 and 1155 specs correctly would automatically notify 1wallet on-chain upon any event of mint or transfer. But a small portion of NFT contracts may fail to follow the spec when they implement their mint and transfer functions. In this case, the manual tracking solution as I proposed in previous comments should be a sufficient remedy. 

The explorer functions differently. It runs on a server, and has the luxury to read, track, and parse all transactions processed on-chain. 1wallet is meant to be server-less and does not hav the luxury. Accordingly, the explorer may monitor on-chain event emissions and compute balance of all accounts (1wallet or not). But since it relies on event emissions, it can be fooled using forged event names and signatures, and so the balance it computes may be inaccurate. For the purpose of block explorer, inaccuracy is acceptable. For wallet, it would not be. Therefore I decided not to use information from the block explorer directly, though in the future I may utilize their APIs to complement tracking. Another downside of the explorer is its monitoring and indexing of the event emissions are often delayed, and may neglect many types of NFTs. During testing, I found many NFTs I implemented for testing was not correctly tracked by the explorer.

**Comment by Tailchakra** [comment]
Were these NFTs sent with the safeTransferFrom or the transferFrom function?

**Comment by polymorpher** [comment]
> Were these NFTs sent with the safeTransferFrom or the transferFrom function?

I think I saw signatures of these functions in transaction history / log. Need to double check again.

**Comment by polymorpher** [comment]
https://github.com/polymorpher/one-wallet/pull/154 added buttons to let users track/untrack NFT and tokens manually. The tracking is local - so the wallet smart contract won't be able to auto-transfer / auto-recover these NFTs when an upgrade or recovery is triggered. However, I will improve Upgrade process in the future to let users sync local/remote tracking states. I will also add a feature to let users inspect and control pre-upgrade wallets after they upgrade, so they can manually transfer out any asset left over.
