### ISSUE TITLE
Could not create new wallet with Authy app

### ISSUE THREAD

**Issue by vuquangbinh** [polymorpher/one-wallet#145]
Hi,

Please support to create new 1wallet with Authy app because Authy is more easy and convenient than Google Authenticator.

**Comment by polymorpher** [comment]
Sorry, can't do it because Authy doesn't support exporting an account, which means the wallet associated with the account won't be restorable on any device. See also https://github.com/polymorpher/one-wallet/issues/109 https://github.com/polymorpher/one-wallet/issues/50. I intentionally made it unscannable in Authy.

**Comment by vuquangbinh** [comment]
Thanks for your reply!
