### ISSUE TITLE
Google Authenticator does not recognize 1Wallet QR code 

### ISSUE THREAD

**Issue by dproietti8** [polymorpher/one-wallet#161]
Google Authenticator does not recognize my QR code after export. I now have funds locked in my 1wallet that I can not access. How do I get Authenticator to recognize my 1wallet?

**Comment by polymorpher** [comment]
What did you export, to where, and what QR code was not recognized, while you are doing what?

**Comment by DogPro88** [comment]
I exported the QR code from Google Authenticator to open on another phone. I get an error "Invalid Barcode not authentication token barcode".  I checked my recovery address and it's only sending to my newly created 1wallet, not to my recovery address. So from what I'm seeing, these funds are now lost!

**Comment by polymorpher** [comment]
There are a few very ambiguous things in what you said that require some clarification:
1.  It is unclear what you meant by "to open on another phone". What "opened" the QR code? It also does not make sense to "open" a QR code.
2. When you export a Google Authenticator entry (a.k.a account) as a QR code, the original entry would not disappear unless you specifically ask Google Authenticator to delete it after you export the entry. It is unclear whether you did so. If you did not, then it follows the action you performed would be harmless, because the entry was still there. If you did, it seems you did something you should not have done, and the issue at question becomes how you recover your funds after you mistakenly deleted your Google Authenticator entry without any backup. Which is the case?
3. "Invalid Barcode not authentication token barcode" is not an error 1wallet would produce. Where did you get this error?
4. You said you "checked my recovery address" and "it's only sending to my newly created 1wallet". What is "it"? Is "it" the recovery address, or the address which you want to recover funds from? It also unclear why you expect something is sent (to whichever address) - what action did you take, and what is the expected result? 
5. What is your 1wallet address, recovery address, or a transaction id such that there is something I can lookup to find out what happened?
6. It is unclear how you reached the conclusion "So from what I'm seeing, these funds are now lost!" - it does not seem to logically follow any preceding statement.

**Comment by DogPro88** [comment]
1. Answer: I was transferring Authenticator to a new device. I went to EXPORT on the google authenticator.
2. Answer: I mistakenly deleted google Authenticator when trying to export a QR code. 
3. Answer: when trying to recover my google authentication for my 1wallet. 
4. Answer: it’s not sending the funds to the recovery address. It appears the recovery address is my 1wallet, not my external One wallet where the ONE was originally transferred from. 
5. What is your 1wallet address, recovery address, or a transaction id such that there is something I can look up to find out what happened? 
6. Answer: 1Wallet address is: one15jy0c4ew4jagc3ajefgaehxper46vpjrl9gkl0
      
Recovery address:  one17h4q60q2x973dzug2wxrmzg47rtvv2dw34jkn3

Transaction: https://explorer.harmony.one/tx/0x80e684cf0cc6c14ca90b9408293650e9945cfa39b0c0c339171989f291cc78b7?activeTab=0

https://explorer.harmony.one/tx/0xeaff6240f0bc455c34b00d8fad6b497d6938f5c7a43d567c04ecaad86eb7156d

7. Answer: Assuming I lost access to google authenticator, I can’t verify the wallet. I hope this isn’t the case. 

Thank you

**Comment by polymorpher** [comment]
I looked it up. Your recovery address was never set. It is the default one, `0x02F2cF45DD4bAcbA091D78502Dba3B2F431a54D3`, also known as 1wallet DAO, which is controlled by a MultiSig Safe that requires 3 out of 5 signatures. I will have a discussion with those who control the safe and see what we can do

The "recovery address" you listed (`one17h4q60q2x973dzug2wxrmzg47rtvv2dw34jkn3`) is not your recovery address. It appears to be the address that sent funds to the 1wallet.

**Comment by polymorpher** [comment]
Can you do the recovery now? Once funds are in 1wallet DAO, we will send them to `one17h4q60q2x973dzug2wxrmzg47rtvv2dw34jkn3` where the funds originally came from

**Comment by DogPro88** [comment]
Yes
________________________________
