### ISSUE TITLE
Loss of Funds in 1Wallet After Update 

### ISSUE THREAD

**Issue by thehighindian** [polymorpher/one-wallet#184]
Hello, after updating my 1wallet I lost a significant amount of $ONE. My NFT's did transfer over and only a partial amount of my balance.

**Comment by polymorpher** [comment]
What's your address?

**Comment by thehighindian** [comment]
one1ptygn6ehdyuzr7ljanu9swp262y7px9r2da2m2

**Comment by thehighindian** [comment]
I believe this is where the leftover balance is here https://explorer.harmony.one/address/0x58f599ec48a15cfbcacf8cb57f26d379ceb8797f

I attempted to restore this address but it says it already exists locally

**Comment by polymorpher** [comment]
Do this: go to About page of the (post-upgrade) wallet, click the old address in "Upgraded From", and click Inspect. After that, go to "Recover" tab and start a recovery. It will transfer all assets to the (post-upgrade) address

![image](https://user-images.githubusercontent.com/913871/140235141-9019a8b0-88ba-44a7-b0d7-4eca65a247e6.png)


During upgrade, since you did not have a recovery address, your recovery address is automatically set to the new address, and the wallet should have transferred all assets to your new address. Currently, the code does not transfer all assets to the new address, instead it only transfer what the daily limit allows. That's an omission, I will fix it in the next version.

**Comment by thehighindian** [comment]
Got it! Thank you!

**Comment by polymorpher** [comment]
As a temporary solution, I made it mandatory for users to set a recovery address before upgrade, if they have a high value wallet. 

![image](https://user-images.githubusercontent.com/913871/140274182-daf26fc4-b1fc-4e7d-a47e-160e7b88a083.png)
